name: test-on-push-and-pr

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ '*' ]

jobs:

  unit_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby_version: [3.2, 3.3]
    steps:
      - uses: actions/checkout@v2
      - name: Set up ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby_version }}
      - name: Run unit tests
        env:
          RUBY_VERSION: ${{ matrix.ruby_version }}
        run: |
          make init 
          find / -name "*.so" 2>/dev/null | grep -i ruby
          make test-unit


  integration_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2
      - name: Run 'pr' target
        run: make pr
